/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OAuthProviderService } from "../oAuthProvider.service";
import { OAuthProviderCreateInput } from "./OAuthProviderCreateInput";
import { OAuthProvider } from "./OAuthProvider";
import { OAuthProviderFindManyArgs } from "./OAuthProviderFindManyArgs";
import { OAuthProviderWhereUniqueInput } from "./OAuthProviderWhereUniqueInput";
import { OAuthProviderUpdateInput } from "./OAuthProviderUpdateInput";

export class OAuthProviderControllerBase {
  constructor(protected readonly service: OAuthProviderService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OAuthProvider })
  async createOAuthProvider(
    @common.Body() data: OAuthProviderCreateInput
  ): Promise<OAuthProvider> {
    return await this.service.createOAuthProvider({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [OAuthProvider] })
  @ApiNestedQuery(OAuthProviderFindManyArgs)
  async oAuthProviders(
    @common.Req() request: Request
  ): Promise<OAuthProvider[]> {
    const args = plainToClass(OAuthProviderFindManyArgs, request.query);
    return this.service.oAuthProviders({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OAuthProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async oAuthProvider(
    @common.Param() params: OAuthProviderWhereUniqueInput
  ): Promise<OAuthProvider | null> {
    const result = await this.service.oAuthProvider({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OAuthProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOAuthProvider(
    @common.Param() params: OAuthProviderWhereUniqueInput,
    @common.Body() data: OAuthProviderUpdateInput
  ): Promise<OAuthProvider | null> {
    try {
      return await this.service.updateOAuthProvider({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OAuthProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOAuthProvider(
    @common.Param() params: OAuthProviderWhereUniqueInput
  ): Promise<OAuthProvider | null> {
    try {
      return await this.service.deleteOAuthProvider({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
