/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { OAuthProvider } from "./OAuthProvider";
import { OAuthProviderCountArgs } from "./OAuthProviderCountArgs";
import { OAuthProviderFindManyArgs } from "./OAuthProviderFindManyArgs";
import { OAuthProviderFindUniqueArgs } from "./OAuthProviderFindUniqueArgs";
import { DeleteOAuthProviderArgs } from "./DeleteOAuthProviderArgs";
import { OAuthProviderService } from "../oAuthProvider.service";
@graphql.Resolver(() => OAuthProvider)
export class OAuthProviderResolverBase {
  constructor(protected readonly service: OAuthProviderService) {}

  async _oAuthProvidersMeta(
    @graphql.Args() args: OAuthProviderCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [OAuthProvider])
  async oAuthProviders(
    @graphql.Args() args: OAuthProviderFindManyArgs
  ): Promise<OAuthProvider[]> {
    return this.service.oAuthProviders(args);
  }

  @graphql.Query(() => OAuthProvider, { nullable: true })
  async oAuthProvider(
    @graphql.Args() args: OAuthProviderFindUniqueArgs
  ): Promise<OAuthProvider | null> {
    const result = await this.service.oAuthProvider(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OAuthProvider)
  async deleteOAuthProvider(
    @graphql.Args() args: DeleteOAuthProviderArgs
  ): Promise<OAuthProvider | null> {
    try {
      return await this.service.deleteOAuthProvider(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
