/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CollaborationDocs } from "./CollaborationDocs";
import { CollaborationDocsCountArgs } from "./CollaborationDocsCountArgs";
import { CollaborationDocsFindManyArgs } from "./CollaborationDocsFindManyArgs";
import { CollaborationDocsFindUniqueArgs } from "./CollaborationDocsFindUniqueArgs";
import { DeleteCollaborationDocsArgs } from "./DeleteCollaborationDocsArgs";
import { CollaborationDocsService } from "../collaborationDocs.service";
@graphql.Resolver(() => CollaborationDocs)
export class CollaborationDocsResolverBase {
  constructor(protected readonly service: CollaborationDocsService) {}

  async _collaborationDocsItemsMeta(
    @graphql.Args() args: CollaborationDocsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CollaborationDocs])
  async collaborationDocsItems(
    @graphql.Args() args: CollaborationDocsFindManyArgs
  ): Promise<CollaborationDocs[]> {
    return this.service.collaborationDocsItems(args);
  }

  @graphql.Query(() => CollaborationDocs, { nullable: true })
  async collaborationDocs(
    @graphql.Args() args: CollaborationDocsFindUniqueArgs
  ): Promise<CollaborationDocs | null> {
    const result = await this.service.collaborationDocs(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CollaborationDocs)
  async deleteCollaborationDocs(
    @graphql.Args() args: DeleteCollaborationDocsArgs
  ): Promise<CollaborationDocs | null> {
    try {
      return await this.service.deleteCollaborationDocs(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
