/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Forms } from "./Forms";
import { FormsCountArgs } from "./FormsCountArgs";
import { FormsFindManyArgs } from "./FormsFindManyArgs";
import { FormsFindUniqueArgs } from "./FormsFindUniqueArgs";
import { DeleteFormsArgs } from "./DeleteFormsArgs";
import { FormsService } from "../forms.service";
@graphql.Resolver(() => Forms)
export class FormsResolverBase {
  constructor(protected readonly service: FormsService) {}

  async _formsItemsMeta(
    @graphql.Args() args: FormsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Forms])
  async formsItems(@graphql.Args() args: FormsFindManyArgs): Promise<Forms[]> {
    return this.service.formsItems(args);
  }

  @graphql.Query(() => Forms, { nullable: true })
  async forms(
    @graphql.Args() args: FormsFindUniqueArgs
  ): Promise<Forms | null> {
    const result = await this.service.forms(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Forms)
  async deleteForms(
    @graphql.Args() args: DeleteFormsArgs
  ): Promise<Forms | null> {
    try {
      return await this.service.deleteForms(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
