/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UniversalSearch } from "./UniversalSearch";
import { UniversalSearchCountArgs } from "./UniversalSearchCountArgs";
import { UniversalSearchFindManyArgs } from "./UniversalSearchFindManyArgs";
import { UniversalSearchFindUniqueArgs } from "./UniversalSearchFindUniqueArgs";
import { DeleteUniversalSearchArgs } from "./DeleteUniversalSearchArgs";
import { UniversalSearchService } from "../universalSearch.service";
@graphql.Resolver(() => UniversalSearch)
export class UniversalSearchResolverBase {
  constructor(protected readonly service: UniversalSearchService) {}

  async _universalSearchesMeta(
    @graphql.Args() args: UniversalSearchCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UniversalSearch])
  async universalSearches(
    @graphql.Args() args: UniversalSearchFindManyArgs
  ): Promise<UniversalSearch[]> {
    return this.service.universalSearches(args);
  }

  @graphql.Query(() => UniversalSearch, { nullable: true })
  async universalSearch(
    @graphql.Args() args: UniversalSearchFindUniqueArgs
  ): Promise<UniversalSearch | null> {
    const result = await this.service.universalSearch(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UniversalSearch)
  async deleteUniversalSearch(
    @graphql.Args() args: DeleteUniversalSearchArgs
  ): Promise<UniversalSearch | null> {
    try {
      return await this.service.deleteUniversalSearch(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
