/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { IntegrationSettings } from "./IntegrationSettings";
import { IntegrationSettingsCountArgs } from "./IntegrationSettingsCountArgs";
import { IntegrationSettingsFindManyArgs } from "./IntegrationSettingsFindManyArgs";
import { IntegrationSettingsFindUniqueArgs } from "./IntegrationSettingsFindUniqueArgs";
import { DeleteIntegrationSettingsArgs } from "./DeleteIntegrationSettingsArgs";
import { IntegrationSettingsService } from "../integrationSettings.service";
@graphql.Resolver(() => IntegrationSettings)
export class IntegrationSettingsResolverBase {
  constructor(protected readonly service: IntegrationSettingsService) {}

  async _integrationSettingsItemsMeta(
    @graphql.Args() args: IntegrationSettingsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [IntegrationSettings])
  async integrationSettingsItems(
    @graphql.Args() args: IntegrationSettingsFindManyArgs
  ): Promise<IntegrationSettings[]> {
    return this.service.integrationSettingsItems(args);
  }

  @graphql.Query(() => IntegrationSettings, { nullable: true })
  async integrationSettings(
    @graphql.Args() args: IntegrationSettingsFindUniqueArgs
  ): Promise<IntegrationSettings | null> {
    const result = await this.service.integrationSettings(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => IntegrationSettings)
  async deleteIntegrationSettings(
    @graphql.Args() args: DeleteIntegrationSettingsArgs
  ): Promise<IntegrationSettings | null> {
    try {
      return await this.service.deleteIntegrationSettings(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
