/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Automations } from "./Automations";
import { AutomationsCountArgs } from "./AutomationsCountArgs";
import { AutomationsFindManyArgs } from "./AutomationsFindManyArgs";
import { AutomationsFindUniqueArgs } from "./AutomationsFindUniqueArgs";
import { DeleteAutomationsArgs } from "./DeleteAutomationsArgs";
import { AutomationsService } from "../automations.service";
@graphql.Resolver(() => Automations)
export class AutomationsResolverBase {
  constructor(protected readonly service: AutomationsService) {}

  async _automationsItemsMeta(
    @graphql.Args() args: AutomationsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Automations])
  async automationsItems(
    @graphql.Args() args: AutomationsFindManyArgs
  ): Promise<Automations[]> {
    return this.service.automationsItems(args);
  }

  @graphql.Query(() => Automations, { nullable: true })
  async automations(
    @graphql.Args() args: AutomationsFindUniqueArgs
  ): Promise<Automations | null> {
    const result = await this.service.automations(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Automations)
  async deleteAutomations(
    @graphql.Args() args: DeleteAutomationsArgs
  ): Promise<Automations | null> {
    try {
      return await this.service.deleteAutomations(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
