/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Wikis as PrismaWikis } from "@prisma/client";

export class WikisServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.WikisCountArgs, "select">): Promise<number> {
    return this.prisma.wikis.count(args);
  }

  async wikisItems<T extends Prisma.WikisFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.WikisFindManyArgs>
  ): Promise<PrismaWikis[]> {
    return this.prisma.wikis.findMany<Prisma.WikisFindManyArgs>(args);
  }
  async wikis<T extends Prisma.WikisFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.WikisFindUniqueArgs>
  ): Promise<PrismaWikis | null> {
    return this.prisma.wikis.findUnique(args);
  }
  async createWikis<T extends Prisma.WikisCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.WikisCreateArgs>
  ): Promise<PrismaWikis> {
    return this.prisma.wikis.create<T>(args);
  }
  async updateWikis<T extends Prisma.WikisUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.WikisUpdateArgs>
  ): Promise<PrismaWikis> {
    return this.prisma.wikis.update<T>(args);
  }
  async deleteWikis<T extends Prisma.WikisDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.WikisDeleteArgs>
  ): Promise<PrismaWikis> {
    return this.prisma.wikis.delete(args);
  }
}
