/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Docs } from "./Docs";
import { DocsCountArgs } from "./DocsCountArgs";
import { DocsFindManyArgs } from "./DocsFindManyArgs";
import { DocsFindUniqueArgs } from "./DocsFindUniqueArgs";
import { DeleteDocsArgs } from "./DeleteDocsArgs";
import { DocsService } from "../docs.service";
@graphql.Resolver(() => Docs)
export class DocsResolverBase {
  constructor(protected readonly service: DocsService) {}

  async _docsItemsMeta(
    @graphql.Args() args: DocsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Docs])
  async docsItems(@graphql.Args() args: DocsFindManyArgs): Promise<Docs[]> {
    return this.service.docsItems(args);
  }

  @graphql.Query(() => Docs, { nullable: true })
  async docs(@graphql.Args() args: DocsFindUniqueArgs): Promise<Docs | null> {
    const result = await this.service.docs(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Docs)
  async deleteDocs(@graphql.Args() args: DeleteDocsArgs): Promise<Docs | null> {
    try {
      return await this.service.deleteDocs(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
