/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AskAi } from "./AskAi";
import { AskAiCountArgs } from "./AskAiCountArgs";
import { AskAiFindManyArgs } from "./AskAiFindManyArgs";
import { AskAiFindUniqueArgs } from "./AskAiFindUniqueArgs";
import { DeleteAskAiArgs } from "./DeleteAskAiArgs";
import { AskAiService } from "../askAi.service";
@graphql.Resolver(() => AskAi)
export class AskAiResolverBase {
  constructor(protected readonly service: AskAiService) {}

  async _askAisMeta(
    @graphql.Args() args: AskAiCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AskAi])
  async askAis(@graphql.Args() args: AskAiFindManyArgs): Promise<AskAi[]> {
    return this.service.askAis(args);
  }

  @graphql.Query(() => AskAi, { nullable: true })
  async askAi(
    @graphql.Args() args: AskAiFindUniqueArgs
  ): Promise<AskAi | null> {
    const result = await this.service.askAi(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AskAi)
  async deleteAskAi(
    @graphql.Args() args: DeleteAskAiArgs
  ): Promise<AskAi | null> {
    try {
      return await this.service.deleteAskAi(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
