/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Goals } from "./Goals";
import { GoalsCountArgs } from "./GoalsCountArgs";
import { GoalsFindManyArgs } from "./GoalsFindManyArgs";
import { GoalsFindUniqueArgs } from "./GoalsFindUniqueArgs";
import { DeleteGoalsArgs } from "./DeleteGoalsArgs";
import { GoalsService } from "../goals.service";
@graphql.Resolver(() => Goals)
export class GoalsResolverBase {
  constructor(protected readonly service: GoalsService) {}

  async _goalsItemsMeta(
    @graphql.Args() args: GoalsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Goals])
  async goalsItems(@graphql.Args() args: GoalsFindManyArgs): Promise<Goals[]> {
    return this.service.goalsItems(args);
  }

  @graphql.Query(() => Goals, { nullable: true })
  async goals(
    @graphql.Args() args: GoalsFindUniqueArgs
  ): Promise<Goals | null> {
    const result = await this.service.goals(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Goals)
  async deleteGoals(
    @graphql.Args() args: DeleteGoalsArgs
  ): Promise<Goals | null> {
    try {
      return await this.service.deleteGoals(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
