/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { GoalsWhereInput } from "./GoalsWhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { GoalsOrderByInput } from "./GoalsOrderByInput";

@ArgsType()
class GoalsFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => GoalsWhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => GoalsWhereInput, { nullable: true })
  @Type(() => GoalsWhereInput)
  where?: GoalsWhereInput;

  @ApiProperty({
    required: false,
    type: [GoalsOrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [GoalsOrderByInput], { nullable: true })
  @Type(() => GoalsOrderByInput)
  orderBy?: Array<GoalsOrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { GoalsFindManyArgs as GoalsFindManyArgs };
