/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Sprints } from "./Sprints";
import { SprintsCountArgs } from "./SprintsCountArgs";
import { SprintsFindManyArgs } from "./SprintsFindManyArgs";
import { SprintsFindUniqueArgs } from "./SprintsFindUniqueArgs";
import { DeleteSprintsArgs } from "./DeleteSprintsArgs";
import { SprintsService } from "../sprints.service";
@graphql.Resolver(() => Sprints)
export class SprintsResolverBase {
  constructor(protected readonly service: SprintsService) {}

  async _sprintsItemsMeta(
    @graphql.Args() args: SprintsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Sprints])
  async sprintsItems(
    @graphql.Args() args: SprintsFindManyArgs
  ): Promise<Sprints[]> {
    return this.service.sprintsItems(args);
  }

  @graphql.Query(() => Sprints, { nullable: true })
  async sprints(
    @graphql.Args() args: SprintsFindUniqueArgs
  ): Promise<Sprints | null> {
    const result = await this.service.sprints(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Sprints)
  async deleteSprints(
    @graphql.Args() args: DeleteSprintsArgs
  ): Promise<Sprints | null> {
    try {
      return await this.service.deleteSprints(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
