/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { GanttCharts } from "./GanttCharts";
import { GanttChartsCountArgs } from "./GanttChartsCountArgs";
import { GanttChartsFindManyArgs } from "./GanttChartsFindManyArgs";
import { GanttChartsFindUniqueArgs } from "./GanttChartsFindUniqueArgs";
import { DeleteGanttChartsArgs } from "./DeleteGanttChartsArgs";
import { GanttChartsService } from "../ganttCharts.service";
@graphql.Resolver(() => GanttCharts)
export class GanttChartsResolverBase {
  constructor(protected readonly service: GanttChartsService) {}

  async _ganttChartsItemsMeta(
    @graphql.Args() args: GanttChartsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [GanttCharts])
  async ganttChartsItems(
    @graphql.Args() args: GanttChartsFindManyArgs
  ): Promise<GanttCharts[]> {
    return this.service.ganttChartsItems(args);
  }

  @graphql.Query(() => GanttCharts, { nullable: true })
  async ganttCharts(
    @graphql.Args() args: GanttChartsFindUniqueArgs
  ): Promise<GanttCharts | null> {
    const result = await this.service.ganttCharts(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => GanttCharts)
  async deleteGanttCharts(
    @graphql.Args() args: DeleteGanttChartsArgs
  ): Promise<GanttCharts | null> {
    try {
      return await this.service.deleteGanttCharts(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
