/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CustomStatuses } from "./CustomStatuses";
import { CustomStatusesCountArgs } from "./CustomStatusesCountArgs";
import { CustomStatusesFindManyArgs } from "./CustomStatusesFindManyArgs";
import { CustomStatusesFindUniqueArgs } from "./CustomStatusesFindUniqueArgs";
import { DeleteCustomStatusesArgs } from "./DeleteCustomStatusesArgs";
import { CustomStatusesService } from "../customStatuses.service";
@graphql.Resolver(() => CustomStatuses)
export class CustomStatusesResolverBase {
  constructor(protected readonly service: CustomStatusesService) {}

  async _customStatusesItemsMeta(
    @graphql.Args() args: CustomStatusesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CustomStatuses])
  async customStatusesItems(
    @graphql.Args() args: CustomStatusesFindManyArgs
  ): Promise<CustomStatuses[]> {
    return this.service.customStatusesItems(args);
  }

  @graphql.Query(() => CustomStatuses, { nullable: true })
  async customStatuses(
    @graphql.Args() args: CustomStatusesFindUniqueArgs
  ): Promise<CustomStatuses | null> {
    const result = await this.service.customStatuses(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CustomStatuses)
  async deleteCustomStatuses(
    @graphql.Args() args: DeleteCustomStatusesArgs
  ): Promise<CustomStatuses | null> {
    try {
      return await this.service.deleteCustomStatuses(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
